VERSION="1.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; November 2021"
ACCOUNTS=[
"GASBV6W7GGED66MXEVC7YZHTWWYMSVYEY35USF2HJZBLABLYIFQGXZY6",
"GCQLPBWOQ5PAJYEEQBE7GDSY7X3LCYKFEBKOCNF3OUA6F74ORK74HVSQ"
]
[DOCUMENTATION]
ORG_NAME="LINK.IO LTD."
ORG_DBA="LINK"
ORG_URL="https://www.linkio.africa/"
ORG_LOGO="https://uploads-ssl.webflow.com/60a70a1080cf2974d4b1595e/61a563ccd5a82c9cee1ae78e_linklogo.png"
ORG_DESCRIPTION="LINK is a Global Cross Border payments platform for the next billion Africans, providing services in a Faster and Cheaper way"
ORG_PHYSICAL_ADDRESS="2 Fredrick Street, Kings Cross, London, United Kingdom WC1X 0ND"
ORG_TWITTER="link_io"
ORG_OFFICIAL_EMAIL="support@linkupio.com"
[[PRINCIPALS]]
name="Evarist Emmanuel"
email="engremmanuelec@gmail.com"
[[PRINCIPALS]]
name="Tomisin Leshi"
email="tomisinleshi@gmail.com"
[[CURRENCIES]]
code="NGNC"
issuer="GASBV6W7GGED66MXEVC7YZHTWWYMSVYEY35USF2HJZBLABLYIFQGXZY6"
image="https://uploads-ssl.webflow.com/60a70a1080cf2974d4b1595e/61a563cdf8821aafa156914d_ngnclogo.png"
desc="Asset backed token pegged 1:1 to Nigerian Naira ₦"
display_decimals=2
is_asset_anchored=true
is_unlimited=true
anchor_asset_type="fiat"
anchor_asset="NGN"
redemption_instructions="contact Authorized Dealers or signup with KYC info on LINK"
status="live"
